// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCylinderPressure(arg1) {
  return window['go']['backend']['GasGun2Controller']['AutoCylinderPressure'](arg1);
}

export function AutoPumpTubePressure(arg1) {
  return window['go']['backend']['GasGun2Controller']['AutoPumpTubePressure'](arg1);
}

export function CloseSwitch(arg1) {
  return window['go']['backend']['GasGun2Controller']['CloseSwitch'](arg1);
}

export function ConnectPLC(arg1) {
  return window['go']['backend']['GasGun2Controller']['ConnectPLC'](arg1);
}

export function DisconnectPLC() {
  return window['go']['backend']['GasGun2Controller']['DisconnectPLC']();
}

export function Fire() {
  return window['go']['backend']['GasGun2Controller']['Fire']();
}

export function GetConfig() {
  return window['go']['backend']['GasGun2Controller']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['backend']['GasGun2Controller']['GetConfigPath']();
}

export function GetRealTimeData() {
  return window['go']['backend']['GasGun2Controller']['GetRealTimeData']();
}

export function Init(arg1) {
  return window['go']['backend']['GasGun2Controller']['Init'](arg1);
}

export function ManualDecompress(arg1) {
  return window['go']['backend']['GasGun2Controller']['ManualDecompress'](arg1);
}

export function ManualPressurize(arg1) {
  return window['go']['backend']['GasGun2Controller']['ManualPressurize'](arg1);
}

export function ManualPumpTubeDecompress(arg1) {
  return window['go']['backend']['GasGun2Controller']['ManualPumpTubeDecompress'](arg1);
}

export function ManualPumpTubePressurize(arg1) {
  return window['go']['backend']['GasGun2Controller']['ManualPumpTubePressurize'](arg1);
}

export function ManualPumpTubeProtect(arg1) {
  return window['go']['backend']['GasGun2Controller']['ManualPumpTubeProtect'](arg1);
}

export function OpenSwitch(arg1) {
  return window['go']['backend']['GasGun2Controller']['OpenSwitch'](arg1);
}

export function PrepareFire() {
  return window['go']['backend']['GasGun2Controller']['PrepareFire']();
}

export function ResetSystem(arg1) {
  return window['go']['backend']['GasGun2Controller']['ResetSystem'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['GasGun2Controller']['SaveConfig'](arg1);
}

export function SetTriggerMode(arg1) {
  return window['go']['backend']['GasGun2Controller']['SetTriggerMode'](arg1);
}

export function StartAutoVacuum() {
  return window['go']['backend']['GasGun2Controller']['StartAutoVacuum']();
}

export function StartPumpTubeVacuum() {
  return window['go']['backend']['GasGun2Controller']['StartPumpTubeVacuum']();
}

export function StopAutoCylinderPressure() {
  return window['go']['backend']['GasGun2Controller']['StopAutoCylinderPressure']();
}

export function StopAutoPumpTubePressure() {
  return window['go']['backend']['GasGun2Controller']['StopAutoPumpTubePressure']();
}

export function StopAutoVacuum() {
  return window['go']['backend']['GasGun2Controller']['StopAutoVacuum']();
}

export function StopPumpTubeVacuum() {
  return window['go']['backend']['GasGun2Controller']['StopPumpTubeVacuum']();
}
