// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function AutoPressurize(arg1:number):Promise<backend.APIResponse>;

export function ConnectPLC(arg1:string):Promise<backend.APIResponse>;

export function DisconnectPLC():Promise<backend.APIResponse>;

export function ExhaustSwitch(arg1:boolean):Promise<backend.APIResponse>;

export function FireSwitch(arg1:number):Promise<backend.APIResponse>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConfigPath():Promise<string>;

export function GetRealTimeData():Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function InletSwitch(arg1:boolean):Promise<backend.APIResponse>;

export function SaveConfig(arg1:Record<string, any>):Promise<backend.APIResponse>;

export function TailVacuumSwitch(arg1:boolean):Promise<backend.APIResponse>;

export function VacuumSwitch(arg1:boolean):Promise<backend.APIResponse>;
