// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function AutoCylinderPressure(arg1:number):Promise<backend.APIResponse>;

export function AutoPumpTubePressure(arg1:number):Promise<backend.APIResponse>;

export function CloseSwitch(arg1:string):Promise<void>;

export function ConnectPLC(arg1:string):Promise<backend.APIResponse>;

export function DisconnectPLC():Promise<backend.APIResponse>;

export function Fire():Promise<backend.APIResponse>;

export function GetConfig():Promise<backend.GasGun2Config>;

export function GetConfigPath():Promise<string>;

export function GetRealTimeData():Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function ManualDecompress(arg1:boolean):Promise<backend.APIResponse>;

export function ManualPressurize(arg1:boolean):Promise<backend.APIResponse>;

export function ManualPumpTubeDecompress(arg1:boolean):Promise<backend.APIResponse>;

export function ManualPumpTubePressurize(arg1:boolean):Promise<backend.APIResponse>;

export function ManualPumpTubeProtect(arg1:boolean):Promise<backend.APIResponse>;

export function OpenSwitch(arg1:string):Promise<void>;

export function PrepareFire():Promise<backend.APIResponse>;

export function ResetSystem(arg1:boolean):Promise<backend.APIResponse>;

export function SaveConfig(arg1:backend.GasGun2Config):Promise<backend.APIResponse>;

export function SetTriggerMode(arg1:boolean):Promise<void>;

export function StartAutoVacuum():Promise<backend.APIResponse>;

export function StartPumpTubeVacuum():Promise<backend.APIResponse>;

export function StopAutoCylinderPressure():Promise<backend.APIResponse>;

export function StopAutoPumpTubePressure():Promise<backend.APIResponse>;

export function StopAutoVacuum():Promise<backend.APIResponse>;

export function StopPumpTubeVacuum():Promise<backend.APIResponse>;
