// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoPressurize(arg1) {
  return window['go']['backend']['GasGun1Controller']['AutoPressurize'](arg1);
}

export function ConnectPLC(arg1) {
  return window['go']['backend']['GasGun1Controller']['ConnectPLC'](arg1);
}

export function DisconnectPLC() {
  return window['go']['backend']['GasGun1Controller']['DisconnectPLC']();
}

export function ExhaustSwitch(arg1) {
  return window['go']['backend']['GasGun1Controller']['ExhaustSwitch'](arg1);
}

export function FireSwitch(arg1) {
  return window['go']['backend']['GasGun1Controller']['FireSwitch'](arg1);
}

export function GetConfig() {
  return window['go']['backend']['GasGun1Controller']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['backend']['GasGun1Controller']['GetConfigPath']();
}

export function GetRealTimeData() {
  return window['go']['backend']['GasGun1Controller']['GetRealTimeData']();
}

export function Init(arg1) {
  return window['go']['backend']['GasGun1Controller']['Init'](arg1);
}

export function InletSwitch(arg1) {
  return window['go']['backend']['GasGun1Controller']['InletSwitch'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['GasGun1Controller']['SaveConfig'](arg1);
}

export function TailVacuumSwitch(arg1) {
  return window['go']['backend']['GasGun1Controller']['TailVacuumSwitch'](arg1);
}

export function VacuumSwitch(arg1) {
  return window['go']['backend']['GasGun1Controller']['VacuumSwitch'](arg1);
}
