// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoPressurize(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['AutoPressurize'](arg1);
}

export function ConnectPLC(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['ConnectPLC'](arg1);
}

export function DisconnectPLC() {
  return window['go']['backend']['NormalHopkinsonContoller']['DisconnectPLC']();
}

export function ExhaustSwitch(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['ExhaustSwitch'](arg1);
}

export function FireSwitch(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['FireSwitch'](arg1);
}

export function GetConfig() {
  return window['go']['backend']['NormalHopkinsonContoller']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['backend']['NormalHopkinsonContoller']['GetConfigPath']();
}

export function GetRealTimeData() {
  return window['go']['backend']['NormalHopkinsonContoller']['GetRealTimeData']();
}

export function Init(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['Init'](arg1);
}

export function InletSwitch(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['InletSwitch'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['NormalHopkinsonContoller']['SaveConfig'](arg1);
}
