// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hepsgasgun1} from '../models';
import {context} from '../models';

export function AddMessageToFrontend(arg1:string):Promise<void>;

export function AutoPressurize(arg1:number):Promise<void>;

export function ConnectDevice(arg1:string):Promise<void>;

export function DisconnectDevice():Promise<void>;

export function ExhaustSwitch(arg1:boolean):Promise<void>;

export function ExportAlarmHistory(arg1:string):Promise<void>;

export function FireSwitch(arg1:number):Promise<void>;

export function GetConfig():Promise<hepsgasgun1.Config>;

export function InletSwitch(arg1:boolean):Promise<void>;

export function PressureSwitch(arg1:boolean):Promise<void>;

export function SaveConfig(arg1:hepsgasgun1.Config):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAutoPressurize():Promise<void>;

export function TailVacuumSwitch(arg1:boolean):Promise<void>;

export function VacuumSwitch(arg1:boolean):Promise<void>;
