// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCylinderPressure(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['AutoCylinderPressure'](arg1);
}

export function AutoPumpTubePressure(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['AutoPumpTubePressure'](arg1);
}

export function CloseSwitch(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['CloseSwitch'](arg1);
}

export function ConnectDevice(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['ConnectDevice'](arg1);
}

export function DisconnectDevice() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['DisconnectDevice']();
}

export function Fire() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['Fire']();
}

export function GetConfig() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['GetConfig']();
}

export function OpenSwitch(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['OpenSwitch'](arg1);
}

export function PrepareFire() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['PrepareFire']();
}

export function ResetSystem(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['ResetSystem'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['SaveConfig'](arg1);
}

export function SetTriggerMode(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['SetTriggerMode'](arg1);
}

export function StartAutoVacuum() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StartAutoVacuum']();
}

export function StartPumpTubeVacuum() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StartPumpTubeVacuum']();
}

export function Startup(arg1) {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['Startup'](arg1);
}

export function StopAutoCylinderPressure() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StopAutoCylinderPressure']();
}

export function StopAutoPumpTubePressure() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StopAutoPumpTubePressure']();
}

export function StopAutoVacuum() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StopAutoVacuum']();
}

export function StopPumpTubeVacuum() {
  return window['go']['xinjiegasgun2']['XinjieGasGun2']['StopPumpTubeVacuum']();
}
