// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {xinjiegasgun2} from '../models';
import {context} from '../models';

export function AutoCylinderPressure(arg1:number):Promise<void>;

export function AutoPumpTubePressure(arg1:number):Promise<void>;

export function CloseSwitch(arg1:string):Promise<void>;

export function ConnectDevice(arg1:string):Promise<void>;

export function DisconnectDevice():Promise<void>;

export function Fire():Promise<void>;

export function GetConfig():Promise<xinjiegasgun2.Config>;

export function OpenSwitch(arg1:string):Promise<void>;

export function PrepareFire():Promise<void>;

export function ResetSystem(arg1:boolean):Promise<void>;

export function SaveConfig(arg1:xinjiegasgun2.Config):Promise<void>;

export function SetTriggerMode(arg1:boolean):Promise<void>;

export function StartAutoVacuum():Promise<void>;

export function StartPumpTubeVacuum():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAutoCylinderPressure():Promise<void>;

export function StopAutoPumpTubePressure():Promise<void>;

export function StopAutoVacuum():Promise<void>;

export function StopPumpTubeVacuum():Promise<void>;
