// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessageToFrontend(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['AddMessageToFrontend'](arg1);
}

export function AutoPressurize(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['AutoPressurize'](arg1);
}

export function ConnectDevice(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['ConnectDevice'](arg1);
}

export function DisconnectDevice() {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['DisconnectDevice']();
}

export function ExhaustSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['ExhaustSwitch'](arg1);
}

export function ExportAlarmHistory(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['ExportAlarmHistory'](arg1);
}

export function FireSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['FireSwitch'](arg1);
}

export function GetConfig() {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['GetConfig']();
}

export function InletSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['InletSwitch'](arg1);
}

export function PressureSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['PressureSwitch'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['SaveConfig'](arg1);
}

export function Startup(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['Startup'](arg1);
}

export function StopAutoPressurize() {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['StopAutoPressurize']();
}

export function TailVacuumSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['TailVacuumSwitch'](arg1);
}

export function VacuumSwitch(arg1) {
  return window['go']['xinjiegasgun1']['XinjieGasGun1']['VacuumSwitch'](arg1);
}
