// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIUpdate() {
  return window['go']['main']['App']['APIUpdate']();
}

export function GetCachedRelease() {
  return window['go']['main']['App']['GetCachedRelease']();
}
